/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ken.mizoguch.webviewer.capai;

import javafx.scene.control.Alert;
import javafx.scene.control.TextArea;

/**
 *
 * @author mizoguch-ken
 */
public class Licenses {

    private final String LICENSES
            = "*** Third Party Licenses ***\n"
            + "\n"
            + "* Gson\n"
            + "Copyright 2008 Google Inc.\n"
            + "\n"
            + "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
            + "you may not use this file except in compliance with the License.\n"
            + "You may obtain a copy of the License at\n"
            + "\n"
            + "    http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, software\n"
            + "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
            + "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
            + "See the License for the specific language governing permissions and\n"
            + "limitations under the License.\n"
            + "\n"
            + "\n"
            + "* Netty/All In One\n"
            + "                            The Netty Project\n"
            + "                            =================\n"
            + "\n"
            + "Please visit the Netty web site for more information:\n"
            + "\n"
            + "  * http://netty.io/\n"
            + "\n"
            + "Copyright 2014 The Netty Project\n"
            + "\n"
            + "The Netty Project licenses this file to you under the Apache License,\n"
            + "version 2.0 (the \"License\"); you may not use this file except in compliance\n"
            + "with the License. You may obtain a copy of the License at:\n"
            + "\n"
            + "  http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, software\n"
            + "distributed under the License is distributed on an \"AS IS\" BASIS, WITHOUT\n"
            + "WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the\n"
            + "License for the specific language governing permissions and limitations\n"
            + "under the License.\n"
            + "\n"
            + "Also, please refer to each LICENSE.<component>.txt file, which is located in\n"
            + "the 'license' directory of the distribution file, for the license terms of the\n"
            + "components that this product depends on.\n"
            + "\n"
            + "-------------------------------------------------------------------------------\n"
            + "This product contains the extensions to Java Collections Framework which has\n"
            + "been derived from the works by JSR-166 EG, Doug Lea, and Jason T. Greene:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.jsr166y.txt (Public Domain)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/\n"
            + "    * http://viewvc.jboss.org/cgi-bin/viewvc.cgi/jbosscache/experimental/jsr166/\n"
            + "\n"
            + "This product contains a modified version of Robert Harder's Public Domain\n"
            + "Base64 Encoder and Decoder, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.base64.txt (Public Domain)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://iharder.sourceforge.net/current/java/base64/\n"
            + "\n"
            + "This product contains a modified portion of 'Webbit', an event based  \n"
            + "WebSocket and HTTP server, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.webbit.txt (BSD License)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/joewalnes/webbit\n"
            + "\n"
            + "This product contains a modified portion of 'SLF4J', a simple logging\n"
            + "facade for Java, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.slf4j.txt (MIT License)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://www.slf4j.org/\n"
            + "\n"
            + "This product contains a modified portion of 'Apache Harmony', an open source\n"
            + "Java SE, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.harmony.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://archive.apache.org/dist/harmony/\n"
            + "\n"
            + "This product contains a modified portion of 'jbzip2', a Java bzip2 compression\n"
            + "and decompression library written by Matthew J. Francis. It can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.jbzip2.txt (MIT License)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://code.google.com/p/jbzip2/\n"
            + "\n"
            + "This product contains a modified portion of 'libdivsufsort', a C API library to construct\n"
            + "the suffix array and the Burrows-Wheeler transformed string for any input string of\n"
            + "a constant-size alphabet written by Yuta Mori. It can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.libdivsufsort.txt (MIT License)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/y-256/libdivsufsort\n"
            + "\n"
            + "This product contains a modified portion of Nitsan Wakart's 'JCTools', Java Concurrency Tools for the JVM,\n"
            + " which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.jctools.txt (ASL2 License)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/JCTools/JCTools\n"
            + "\n"
            + "This product optionally depends on 'JZlib', a re-implementation of zlib in\n"
            + "pure Java, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.jzlib.txt (BSD style License)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://www.jcraft.com/jzlib/\n"
            + "\n"
            + "This product optionally depends on 'Compress-LZF', a Java library for encoding and\n"
            + "decoding data in LZF format, written by Tatu Saloranta. It can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.compress-lzf.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/ning/compress\n"
            + "\n"
            + "This product optionally depends on 'lz4', a LZ4 Java compression\n"
            + "and decompression library written by Adrien Grand. It can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.lz4.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/jpountz/lz4-java\n"
            + "\n"
            + "This product optionally depends on 'lzma-java', a LZMA Java compression\n"
            + "and decompression library, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.lzma-java.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/jponge/lzma-java\n"
            + "\n"
            + "This product contains a modified portion of 'jfastlz', a Java port of FastLZ compression\n"
            + "and decompression library written by William Kinney. It can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.jfastlz.txt (MIT License)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://code.google.com/p/jfastlz/\n"
            + "\n"
            + "This product contains a modified portion of and optionally depends on 'Protocol Buffers', Google's data\n"
            + "interchange format, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.protobuf.txt (New BSD License)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/google/protobuf\n"
            + "\n"
            + "This product optionally depends on 'Bouncy Castle Crypto APIs' to generate\n"
            + "a temporary self-signed X.509 certificate when the JVM does not provide the\n"
            + "equivalent functionality.  It can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.bouncycastle.txt (MIT License)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://www.bouncycastle.org/\n"
            + "\n"
            + "This product optionally depends on 'Snappy', a compression library produced\n"
            + "by Google Inc, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.snappy.txt (New BSD License)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/google/snappy\n"
            + "\n"
            + "This product optionally depends on 'JBoss Marshalling', an alternative Java\n"
            + "serialization API, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.jboss-marshalling.txt (GNU LGPL 2.1)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://www.jboss.org/jbossmarshalling\n"
            + "\n"
            + "This product optionally depends on 'Caliper', Google's micro-\n"
            + "benchmarking framework, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.caliper.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/google/caliper\n"
            + "\n"
            + "This product optionally depends on 'Apache Commons Logging', a logging\n"
            + "framework, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.commons-logging.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://commons.apache.org/logging/\n"
            + "\n"
            + "This product optionally depends on 'Apache Log4J', a logging framework, which\n"
            + "can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.log4j.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://logging.apache.org/log4j/\n"
            + "\n"
            + "This product optionally depends on 'Aalto XML', an ultra-high performance\n"
            + "non-blocking XML processor, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.aalto-xml.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * http://wiki.fasterxml.com/AaltoHome\n"
            + "\n"
            + "This product contains a modified version of 'HPACK', a Java implementation of\n"
            + "the HTTP/2 HPACK algorithm written by Twitter. It can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.hpack.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://github.com/twitter/hpack\n"
            + "\n"
            + "This product contains a modified portion of 'Apache Commons Lang', a Java library\n"
            + "provides utilities for the java.lang API, which can be obtained at:\n"
            + "\n"
            + "  * LICENSE:\n"
            + "    * license/LICENSE.commons-lang.txt (Apache License 2.0)\n"
            + "  * HOMEPAGE:\n"
            + "    * https://commons.apache.org/proper/commons-lang/";

    public void show() {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        TextArea textAera = new TextArea();

        textAera.setText(LICENSES);
        alert.setResizable(true);
        alert.setTitle("Licenses");
        alert.getDialogPane().setHeaderText(null);
        textAera.setEditable(false);
        textAera.setWrapText(true);
        alert.getDialogPane().setContent(textAera);
        alert.show();
    }
}
